import re
import urllib.parse


def parse_frontmatter(text):
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    raw = parts[1]
    body = parts[2]
    fm = {}
    for line in raw.split("\n"):
        line = line.strip()
        if ":" in line:
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            fm[key] = val
    return fm, body


def extract_heading(body):
    for line in body.split("\n"):
        line = line.strip()
        if line.startswith("# ") and not line.startswith("## "):
            return line[2:].strip()
    return ""


def extract_original_name(body):
    m = re.search(r"`([^`]+)`", body)
    return m.group(1) if m else ""


def extract_file_uri(body):
    m = re.search(r"\(file:///([^)]+)\)", body)
    if m:
        return urllib.parse.unquote(m.group(1))
    return ""


def extract_series(body):
    m = re.search(r"\*\*Series:\*\*\s*(.+?)(?:\\n|$)", body)
    if m:
        return m.group(1).strip()
    return ""


def is_vortexy_note(text):
    return "Generated by Vortexy Graph Architect" in text
