import os
import re
import urllib.parse
from datetime import datetime

def sanitize_filename(name):
    illegal = r'[\\/:*?"<>|]'
    clean = re.sub(illegal, "-", name)
    clean = re.sub(r'-+', "-", clean)
    clean = re.sub(r'\s+', " ", clean)
    return clean.strip()

def normalize_author_name(name):
    if not name or name.lower() in ("unknown", "desconocido", "unknown auto"):
        return "Unknown Auto"
    delimiters = r" & | and |;"
    sub_authors = re.split(delimiters, name.strip())
    healed_parts = []
    for part in sub_authors:
        s = part.strip()
        if "," in s and s.count(",") == 1:
            parts = s.split(",")
            if len(parts) == 2:
                s = f"{parts[1].strip()} {parts[0].strip()}"
        s = s.title()
        healed_parts.append(s)
    return " & ".join(healed_parts)

def slugify_category(cat_name):
    if not cat_name:
        return "uncategorized"
    slug = cat_name.lower().strip()
    slug = re.sub(r'[^a-z0-9]+', '-', slug)
    slug = slug.strip('-')
    return slug or "uncategorized"

def make_category_tag(cat_name):
    if not cat_name:
        return "#Uncategorized"
    tag = cat_name.strip()
    tag = re.sub(r'[^a-zA-Z0-9\u00C0-\u024f]+', '_', tag)
    tag = tag.strip('_')
    return f"#{tag}" if tag else "#Uncategorized"

DEFAULT_SUBFOLDER_MAP = {
    "00 General Fiction": ["literature", "fiction", "novel", "story", "cuento", "relato", "novela"],
    "01 Horror": ["horror", "terror", "lovecraft", "king", "macabre", "gothic", "dark fantasy"],
    "02 Fantasy": ["fantasy", "fantasia", "magic", "magia", "sword", "dragon", "elfo", "myth"],
    "03 Science Fiction": ["science fiction", "sci-fi", "scifi", "ciencia ficcion", "space", "dystopia"],
    "04 Crime & Mystery": ["crime", "mystery", "misterio", "detective", "noir", "thriller", "suspense"],
    "05 Romance": ["romance", "love", "amor", "erotic", "erotico", "novela rosa"],
    "06 Historical Fiction": ["historical fiction", "historical novel", "novela historica", "historical"],
    "07 Biography & Autobiography": ["biography", "autobiography", "biografia", "memoir", "vida"],
    "08 Memoir & Self-Help": ["self-help", "autoayuda", "memoir", "personal development", "superacion"],
    "09 History": ["history", "historia", "ancient", "medieval", "war", "guerra", "civilization"],
    "10 Technical & Programming": ["technical", "programming", "programacion", "computer", "software", "code", "engineering", "technology"],
    "11 Philosophy": ["philosophy", "filosofia", "ethics", "logic", "pensamiento", "wisdom"],
    "12 Business & Economics": ["business", "economics", "economia", "management", "finance", "marketing", "entrepreneur"],
    "13 Science & Technology": ["science", "technology", "tecnologia", "physics", "chemistry", "biology", "math"],
    "14 Graphic & Literary Arts": ["graphic", "literary arts", "arte", "comic", "graphic novel", "poetry", "poesia"],
    "15 Media & Archive": ["media", "archive", "reference", "reference", "diccionario", "encyclopedia"],
}

def find_subfolder(cat_name, subfolder_map=None):
    if not cat_name:
        return None
    if subfolder_map is None:
        subfolder_map = DEFAULT_SUBFOLDER_MAP
    cat_lower = cat_name.lower().strip()
    for folder, keywords in subfolder_map.items():
        for kw in keywords:
            if kw in cat_lower or cat_lower in kw:
                return folder
    return None

def make_obsidian_content(author, title, category, isbn, original_name, file_uri, version="v1.5.0", series="", volume="", chapter=""):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cat_slug = slugify_category(category)
    cat_tag = make_category_tag(category)
    isbn_display = ""
    if isbn:
        isbn_clean = re.sub(r'[^0-9Xx]', '', isbn)
        if isbn_clean:
            isbn_display = f"\n- **ISBN:** [{isbn_clean}](https://openlibrary.org/isbn/{isbn_clean})"
    file_link = ""
    if file_uri:
        safe_uri = "file:///" + urllib.parse.quote(str(file_uri).replace("\\", "/"))
        file_link = f"\n> [!abstract] File Link\n> [Open Local File]({safe_uri})"
    series_line = ""
    if series:
        vol = f" #{volume}" if volume else ""
        series_line = f"\n- **Series:** {series}{vol}"
    chapter_line = ""
    if chapter:
        chapter_line = f"\n- **Chapter:** {chapter}"

    fm_series = f'\nseries: "{series}"' if series else ""
    fm_volume = f'\nvolume: "{volume}"' if volume else ""
    fm_chapter = f'\nchapter: "{chapter}"' if chapter else ""

    content = f"""---
title: "{title}"
author: "[[{author}]]"
category: {category}
tags: [vortexy, {cat_slug}]
isbn: "{isbn or ''}"{fm_series}{fm_volume}{fm_chapter}
date_organized: {timestamp}
vortexy_version: {version}
---

# {title}

- **Author:** [[{author}]]
- **Category:** {cat_tag}{isbn_display}{series_line}{chapter_line}
- **Original Name:** `{original_name}`{file_link}

---
*Generated by Vortexy Graph Architect*
"""
    return content

def create_obsidian_note(config, meta, skip_if_exists=True, note_index=None, target_vault=None, silent=False):
    if not config.get("obsidian_enabled"):
        return {"status": "error", "error": "Obsidian integration disabled"}
    vault_path = target_vault or config.get("obsidian_vault")
    if not vault_path:
        return {"status": "error", "error": "Vault path not set"}
    filename = meta.get("filename", "")
    skip_exts = (".vtt", ".srt", ".djvu", ".mp3", ".mp4", ".jpg", ".png")
    if filename.lower().endswith(skip_exts):
        return {"status": "exists"}
    author_raw = meta.get("author") or "Unknown Auto"
    if author_raw in ("Unknown", "Unknown Auto"):
        return {"status": "exists"}
    if not os.path.exists(vault_path):
        try:
            os.makedirs(vault_path, exist_ok=True)
        except Exception as e:
            return {"status": "error", "error": f"Could not create vault path: {e}"}
    author = normalize_author_name(author_raw)
    category = meta.get("category") or "Uncategorized"
    cat_name = category
    cats = config.get("categories", {})
    if isinstance(cats, dict) and category in cats:
        cat_info = cats[category]
        if isinstance(cat_info, dict):
            cat_name = cat_info.get("name", category)
    title = meta.get("new_name") or meta.get("filename")
    isbn = meta.get("isbn") or ""
    final_path = meta.get("final_path")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    if author != author_raw:
        old_note_title = sanitize_filename(f"{author_raw} - {title}")
        old_note_path = os.path.join(vault_path, f"{old_note_title}.md")
        if os.path.exists(old_note_path):
            try:
                os.remove(old_note_path)
            except Exception:
                pass
    if title.lower().startswith(author.lower()):
        note_title = sanitize_filename(title)
    else:
        note_title = sanitize_filename(f"{author} - {title}")
    note_path = os.path.join(vault_path, f"{note_title}.md")
    note_name_md = f"{note_title}.md"
    if note_index is not None:
        if note_name_md in note_index:
            return {"status": "exists"}
    elif os.path.exists(note_path):
        return {"status": "exists"}
    content = make_obsidian_content(
        author=author,
        title=title,
        category=cat_name,
        isbn=isbn,
        original_name=filename,
        file_uri=final_path,
        version=config.get('version', 'latest')
    )
    try:
        with open(note_path, "w", encoding="utf-8") as f:
            f.write(content)
        if not silent:
            print(f"Note created: {os.path.basename(note_path)}")
        return {"status": "created"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
