#!/usr/bin/env python3
"""
Fix Obsidian MD Notes — fixes filenames, frontmatter, content, and subfolder
placement for Vortexy-generated notes in the Obsidian vault.

Usage:
    python fix_obsidian_notes.py                     # fix everything
    python fix_obsidian_notes.py --dry-run            # preview only
    python fix_obsidian_notes.py --limit 100          # first 100 notes
    python fix_obsidian_notes.py --vault "G:\\...\\Library"
    python fix_obsidian_notes.py --library "D:\02 Library"
    python fix_obsidian_notes.py --organize           # move notes into subfolders
"""

import os
import re
import sys
import json
import argparse
import urllib.parse
from datetime import datetime

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, CORE_DIR)

from core.vortexy_obsidian import (
    sanitize_filename, normalize_author_name, slugify_category,
    make_category_tag, make_obsidian_content, find_subfolder,
    DEFAULT_SUBFOLDER_MAP
)

# ── CONFIG ──────────────────────────────────────────────────────────────────
CONFIG_PATH = os.path.join(CORE_DIR, "config.json")

def load_config():
    if not os.path.exists(CONFIG_PATH):
        print(f"Config file not found: {CONFIG_PATH}")
        print("Create config.json from the template or use CLI flags.")
        sys.exit(1)
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    cfg.pop("_description", None)
    cfg.pop("_notes", None)

    # .env overrides for common paths (optional, python-dotnet required)
    env_vault = os.environ.get("VAULT_PATH")
    env_library = os.environ.get("LIBRARY_PATH")
    env_organize = os.environ.get("ORGANIZE_NOTES")
    if env_vault:
        cfg["vault_path"] = env_vault
    if env_library:
        cfg["library_path"] = env_library
    if env_organize and env_organize.lower() in ("true", "1", "yes"):
        cfg["organize"] = True

    return cfg

# Known bogus prefixes from backfill path parsing (case-insensitive)
BAD_PREFIXES = {"an", "el", "los", "la", "mi", "no", "lg", "m", "dune", "dragon",
                "stephen", "charles", "patricia", "historia", "platon", "homero",
                "isabel", "gabriel", "mao"}
NUM_PREFIX_RE = re.compile(r"^\d{1,2}\s*-\s+")

# ── HELPERS ─────────────────────────────────────────────────────────────────

def parse_frontmatter(text):
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    raw = parts[1]
    body = parts[2]
    fm = {}
    for line in raw.split("\n"):
        line = line.strip()
        if ":" in line:
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            fm[key] = val
    return fm, body

def extract_heading(body):
    for line in body.split("\n"):
        line = line.strip()
        if line.startswith("# ") and not line.startswith("## "):
            return line[2:].strip()
    return ""

def extract_original_name(body):
    m = re.search(r"`([^`]+)`", body)
    return m.group(1) if m else ""

def extract_file_uri(body):
    m = re.search(r"\(file:///([^)]+)\)", body)
    if m:
        return urllib.parse.unquote(m.group(1))
    return ""

def is_vortexy_note(text):
    return "Generated by Vortexy Graph Architect" in text

def find_pdf_in_library(original_name, library_root):
    if not original_name or not os.path.exists(library_root):
        return None
    for root, dirs, files in os.walk(library_root):
        for f in files:
            if f.lower() == original_name.lower():
                return os.path.join(root, f)
            if os.path.splitext(f)[0].lower() == os.path.splitext(original_name)[0].lower():
                return os.path.join(root, f)
    return None

def parse_author_title_from_filename(filename):
    name_no_ext = os.path.splitext(filename)[0]
    for sep in [" - ", " -", "- "]:
        if sep in name_no_ext:
            segments = [s.strip() for s in name_no_ext.split(sep) if s.strip()]
            if len(segments) >= 2:
                return segments[0], " - ".join(segments[1:])
    return None, name_no_ext

def strip_bad_prefix(raw):
    raw = NUM_PREFIX_RE.sub("", raw)
    for sep in [" - ", " _ ", " - "]:
        if sep in raw:
            first, rest = raw.split(sep, 1)
            if first.strip().lower() in BAD_PREFIXES:
                return rest.strip(), first.strip()
    return raw, None

# ── MAIN FIXER ──────────────────────────────────────────────────────────────

def fix_notes(vault_path, library_path, dry_run, limit, force, organize, cfg):
    if not os.path.exists(vault_path):
        print(f"Vault path not found: {vault_path}")
        sys.exit(1)

    all_items = [f for f in os.listdir(vault_path) if f.endswith(".md")]
    if not all_items:
        print("No .md files found in vault.")
        return

    # Build subfolder index from config map or existing folders
    subfolder_map = cfg.get("subfolder_map", DEFAULT_SUBFOLDER_MAP)
    existing_subfolders = {}
    if organize and os.path.exists(vault_path):
        for item in os.listdir(vault_path):
            item_path = os.path.join(vault_path, item)
            if os.path.isdir(item_path):
                existing_subfolders[item] = item_path

    print(f"Found {len(all_items)} .md files in vault.")
    if limit:
        all_items = all_items[:limit]
        print(f"Processing first {limit} notes...")

    stats = {"fixed": 0, "renamed": 0, "moved": 0, "skipped": 0, "orphaned": 0}

    for idx, fname in enumerate(all_items):
        filepath = os.path.join(vault_path, fname)
        if os.path.isdir(filepath):
            continue

        try:
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                text = f.read()
        except Exception as e:
            print(f"  [!] Error reading {fname}: {e}")
            stats["skipped"] += 1
            continue

        if not is_vortexy_note(text):
            stats["orphaned"] += 1
            continue

        # Parse existing content
        fm, body = parse_frontmatter(text)

        existing_author = fm.get("author", "")
        existing_author = existing_author.strip("[]").strip()
        existing_category = fm.get("category", "Uncategorized")
        existing_isbn = fm.get("isbn", "")
        existing_title = extract_heading(body) or ""
        original_name = extract_original_name(body) or ""
        file_uri = extract_file_uri(body) or ""

        # ── Author / Title detection ──
        # Priority 1: PDF file on disk (most reliable filename)
        pdf_path = None
        if file_uri and os.path.exists(file_uri):
            pdf_path = file_uri
        elif original_name and library_path:
            found = find_pdf_in_library(original_name, library_path)
            if found:
                pdf_path = found
                file_uri = found

        author = "Unknown Auto"
        title = ""
        pdf_has_sep = False

        if pdf_path:
            pdf_fname = os.path.basename(pdf_path)
            f_author, f_title = parse_author_title_from_filename(pdf_fname)
            if f_author:
                author = normalize_author_name(f_author)
                title = f_title
                pdf_has_sep = True
            else:
                title = os.path.splitext(pdf_fname)[0]

        # Priority 2: existing frontmatter if PDF didn't give us a clean author
        if author == "Unknown Auto" and existing_author:
            ex = existing_author.strip().lower()
            if ex and ex not in ("unknown", "desconocido", "") and ex not in BAD_PREFIXES:
                author = normalize_author_name(existing_author)

        # Priority 3: strip bad/num prefix from note filename, then parse author/title from remainder
        if author == "Unknown Auto":
            clean_raw, _ = strip_bad_prefix(fname)
            clean_raw = NUM_PREFIX_RE.sub("", clean_raw)
            f_author, f_title = parse_author_title_from_filename(clean_raw.replace(".md", ""))
            if f_author and f_author.lower() not in BAD_PREFIXES:
                author = normalize_author_name(f_author)
                if not title:
                    title = f_title

        # Title fallback: existing heading, then clean note filename
        if not title:
            if existing_title:
                title = existing_title
            else:
                clean_raw, _ = strip_bad_prefix(fname.replace(".md", ""))
                title = clean_raw
        title = re.sub(r'\.pdf$', '', title, flags=re.IGNORECASE).strip()

        # Build correct filename
        if title.lower().startswith(author.lower()):
            correct_name = sanitize_filename(title)
        else:
            correct_name = sanitize_filename(f"{author} - {title}")
        correct_filename = f"{correct_name}.md"

        # Determine target subfolder
        target_subfolder = None
        if organize:
            subfolder = find_subfolder(existing_category, subfolder_map)
            if subfolder and subfolder in existing_subfolders:
                target_subfolder = subfolder

        target_dir = vault_path
        if target_subfolder:
            target_dir = existing_subfolders[target_subfolder]

        target_path = os.path.join(target_dir, correct_filename)

        needs_rename = (os.path.normpath(filepath) != os.path.normpath(target_path))
        needs_rewrite = True  # always rewrite content

        # Skip if nothing to do
        if not needs_rename and not needs_rewrite and not force:
            stats["skipped"] += 1
            continue

        # Generate new content
        new_content = make_obsidian_content(
            author=author,
            title=title,
            category=existing_category,
            isbn=existing_isbn,
            original_name=original_name,
            file_uri=file_uri or pdf_path,
        )

        if dry_run:
            msg = f"  [{idx+1}] {fname}"
            if needs_rename:
                sub_info = f" [{target_subfolder}/]" if target_subfolder else ""
                msg += f"\n        -> rename to: {sub_info}{correct_filename}"
            msg += " (content rewrite)"
            if author == "Unknown Auto":
                msg += " [author: Unknown Auto]"
            print(msg)
            stats["fixed"] += 1
            continue

        # Write new content (create subfolder if needed)
        if target_subfolder:
            os.makedirs(target_dir, exist_ok=True)

        # Write to temp path first, then handle removal of old
        try:
            with open(target_path, "w", encoding="utf-8") as f:
                f.write(new_content)

            if needs_rename and os.path.normpath(filepath) != os.path.normpath(target_path):
                if os.path.exists(filepath):
                    os.remove(filepath)
                stats["renamed"] += 1
                print(f"  [{idx+1}] {fname} -> {correct_filename}")
            else:
                print(f"  [{idx+1}] {fname} (rewritten)")

            stats["fixed"] += 1
            if target_subfolder and os.path.dirname(filepath) != target_dir:
                stats["moved"] += 1
        except Exception as e:
            print(f"  [!] Error writing {correct_filename}: {e}")
            stats["skipped"] += 1

    # Stats summary
    print("\n" + "=" * 50)
    print(f"  Fixed:     {stats['fixed']}")
    print(f"  Renamed:   {stats['renamed']}")
    print(f"  Moved:     {stats['moved']}")
    print(f"  Skipped:   {stats['skipped']}")
    print(f"  Orphaned:  {stats['orphaned']} (non-Vortexy notes)")
    print("=" * 50)

# ── CLI ─────────────────────────────────────────────────────────────────────

def main():
    cfg = load_config()
    default_vault = cfg.get("vault_path", "")
    default_library = cfg.get("library_path", "")
    default_organize = cfg.get("organize", False)

    parser = argparse.ArgumentParser(description="Fix Obsidian MD Notes from Vortexy")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing")
    parser.add_argument("--limit", type=int, default=0, help="Process only first N notes")
    parser.add_argument("--force", action="store_true", help="Rewrite even if filename is already correct")
    parser.add_argument("--vault", default=default_vault, help=f"Obsidian vault path (from config.json)")
    parser.add_argument("--library", default=default_library, help=f"PDF library path (from config.json)")
    parser.add_argument("--organize", action="store_true", default=default_organize, help="Move notes into subfolders by category (from config.json)")
    args = parser.parse_args()

    fix_notes(
        vault_path=args.vault,
        library_path=args.library,
        dry_run=args.dry_run,
        limit=args.limit,
        force=args.force,
        organize=args.organize,
        cfg=cfg,
    )

if __name__ == "__main__":
    main()
