#!/usr/bin/env python3
"""Merge duplicate markdown notes: extension-duplicates and fuzzy title duplicates."""

import os
import re
import sys
import urllib.parse
from collections import defaultdict
from datetime import datetime

CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, CORE_DIR)

from core.vortexy_parsers import parse_frontmatter, extract_heading, extract_original_name


EXT_PATTERN = re.compile(r'^(.*)\.(txt|epub|mobi|azw3|pdf|djvu|mp3|m4a|wma|wav|flac|ogg)\.md$', re.IGNORECASE)
LINK_RE = re.compile(r'\[Open Local File\]\(([^)]+)\)')
ARTICLES = {'le', 'la', 'les', 'el', 'los', 'las', 'il', 'lo', 'gli', 'der', 'die', 'das'}


def _norm_title(t):
    t = t.lower().strip()
    t = re.sub(r'[^\w\s]', '', t)
    words = [w for w in t.split() if w not in ARTICLES]
    return ' '.join(words)


def merge_extension_duplicates(vault_path, dry_run=False):
    entries = {}
    for entry in os.scandir(vault_path):
        if not entry.is_file() or not entry.name.endswith('.md'):
            continue
        m = EXT_PATTERN.match(entry.name)
        if m:
            base = m.group(1).strip()
            ext = m.group(2).lower()
            entries.setdefault(base, {})[f'.{ext}.md'] = entry.path
        else:
            entries.setdefault(entry.name[:-3], {})['.md'] = entry.path

    count = 0
    for base_key, variants in entries.items():
        ext_md = [k for k in variants if k != '.md']
        if not ext_md or '.md' not in variants:
            continue
        clean_path = variants['.md']

        all_links = []
        all_titles = []
        authors = set()
        categories = set()
        isbns = set()
        original_names = set()
        all_bodies = []

        for variant_key, variant_path in variants.items():
            try:
                with open(variant_path, 'r', encoding='utf-8', errors='replace') as f:
                    text = f.read()
            except Exception:
                continue
            fm, body = parse_frontmatter(text)
            all_links.extend(LINK_RE.findall(body))
            heading = extract_heading(body)
            if heading:
                all_titles.append(heading)
            if fm.get('author'):
                authors.add(fm['author'].strip('[]').strip())
            if fm.get('category'):
                categories.add(fm['category'])
            if fm.get('isbn'):
                isbns.add(fm['isbn'])
            orig = extract_original_name(body)
            if orig:
                original_names.add(orig)
            all_bodies.append(body)

        if len(all_links) < 2:
            continue

        unique_links = list(dict.fromkeys(all_links))
        best_title = max(all_titles, key=len) if all_titles else max(variants.keys(), key=len)
        best_title = re.sub(r'\.(txt|epub|mobi|azw3|pdf|djvu)$', '', best_title, flags=re.IGNORECASE).strip()
        author = next((a for a in authors if a not in ('Unknown', 'Unknown Author')), 'Unknown Author')
        category = next((c for c in categories if c != 'Uncategorized'), '00 General Fiction')
        isbn = next((i for i in isbns if i), '')

        from core.vortexy_obsidian import sanitize_filename, make_category_tag, slugify_category
        date_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        cat_tag = make_category_tag(category)
        cat_slug = slugify_category(category)
        original_name_str = '; '.join(sorted(original_names)) if original_names else ''

        lines = []
        lines.append("---")
        lines.append(f'title: "{best_title}"')
        lines.append(f'author: "[[{author}]]"')
        lines.append(f"category: {category}")
        lines.append(f"tags: [vortexy, {cat_slug}]")
        lines.append(f'isbn: "{isbn}"')
        lines.append(f"date_organized: {date_str}")
        lines.append("vortexy_version: v1.5.0")
        lines.append("---")
        lines.append("")
        lines.append(f"# {best_title}")
        lines.append("")
        lines.append(f"- **Author:** [[{author}]]")
        lines.append(f"- **Category:** {cat_tag}")
        if original_name_str:
            lines.append(f"- **Original Name:** `{original_name_str}`")
        for link in unique_links:
            safe_uri = "file:///" + urllib.parse.quote(str(link).replace("\\", "/"))
            lines.append(f"> [!abstract] File Link")
            lines.append(f"> [Open Local File]({safe_uri})")
            lines.append("")
        lines.append("---")
        lines.append("*Generated by Vortexy Graph Architect*")

        new_content = "\n".join(lines) + "\n"
        correct_name = sanitize_filename(f"{author} - {best_title}")
        target_path = os.path.join(vault_path, f"{correct_name}.md")

        if dry_run:
            print(f"   [merge-ext] Would merge: {correct_name}.md ({len(variants)} files, {len(unique_links)} links)")
            count += 1
            continue

        with open(target_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        for variant_key, variant_path in variants.items():
            if os.path.normpath(variant_path) != os.path.normpath(target_path) and os.path.exists(variant_path):
                try:
                    os.remove(variant_path)
                except Exception:
                    pass
        print(f"   [merge-ext] {correct_name} ({len(variants)} files, {len(unique_links)} links)")
        count += 1

    return count


def merge_fuzzy_duplicates(vault_path, dry_run=False):
    groups = defaultdict(list)

    for entry in os.scandir(vault_path):
        if not entry.is_file() or not entry.name.endswith('.md'):
            continue
        try:
            with open(entry.path, 'r', encoding='utf-8', errors='replace') as f:
                text = f.read()
        except Exception:
            continue
        fm, body = parse_frontmatter(text)
        author = fm.get("author", "").strip("[]").strip()
        title = extract_heading(body) or ""
        if not author or not title or author in ("Unknown", "Unknown Author"):
            continue
        nk = (author.lower().strip(), _norm_title(title))
        groups[nk].append((entry.path, title))

    count = 0
    for (author_key, _), files in groups.items():
        if len(files) < 2:
            continue
        best_title = max(set(t for _, t in files), key=len)
        links = []
        seen_links = set()
        for filepath, _ in files:
            try:
                with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
                    content = f.read()
            except Exception:
                continue
            for m in re.finditer(r'\[Open Local File\]\(([^)]+)\)', content):
                if m.group(1) not in seen_links:
                    seen_links.add(m.group(1))
                    links.append(m.group(1))
        if len(links) < 2:
            continue

        from core.vortexy_obsidian import sanitize_filename, make_category_tag, slugify_category
        date_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        cat = "00 General Fiction"

        lines = []
        lines.append("---")
        lines.append(f'title: "{best_title}"')
        lines.append(f'author: "[[{files[0][1]}]]"')
        lines.append(f"category: {cat}")
        lines.append(f"tags: [vortexy, {slugify_category(cat)}]")
        lines.append('isbn: ""')
        lines.append(f"date_organized: {date_str}")
        lines.append("vortexy_version: v1.5.0")
        lines.append("---")
        lines.append("")
        lines.append(f"# {best_title}")
        lines.append("")
        lines.append(f"- **Author:** [[{files[0][1]}]]")
        lines.append(f"- **Category:** {make_category_tag(cat)}")
        lines.append("")
        for link in links:
            lines.append(f"> [!abstract] File Link")
            lines.append(f"> [Open Local File]({link})")
            lines.append("")
        lines.append("---")
        lines.append("*Generated by Vortexy Graph Architect*")

        new_content = "\n".join(lines) + "\n"
        correct_name = sanitize_filename(f"{files[0][1]} - {best_title}")
        target_path = os.path.join(vault_path, f"{correct_name}.md")

        if dry_run:
            print(f"   [fuzzy-merge] Would merge: {correct_name}.md ({len(files)} files, {len(links)} links)")
            count += 1
            continue

        with open(target_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        for filepath, _ in files:
            try:
                os.remove(filepath)
            except Exception:
                pass
        print(f"   [fuzzy-merge] {correct_name} ({len(files)} files, {len(links)} links)")
        count += 1

    return count
