#!/usr/bin/env python3
"""Vault health report — quick dashboard of vault state."""

import json
import os
import re
import sys
import argparse
from collections import defaultdict

CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, CORE_DIR)

from core.vortexy_config import load_config
from core.vortexy_parsers import parse_frontmatter, extract_heading


def vault_report(vault_path, json_out=False, details=False):
    if not os.path.exists(vault_path):
        print(f"Vault path not found: {vault_path}")
        sys.exit(1)

    md_files = []
    subfolder_counts = defaultdict(int)
    root_files = []

    for entry in os.scandir(vault_path):
        if entry.is_dir():
            sub_count = sum(1 for e in os.scandir(entry.path) if e.name.endswith(".md"))
            if sub_count > 0:
                subfolder_counts[entry.name] = sub_count
            md_files.extend(
                os.path.join(entry.name, e.name)
                for e in os.scandir(entry.path) if e.name.endswith(".md")
            )
        elif entry.name.endswith(".md"):
            root_files.append(entry.name)
            md_files.append(entry.name)

    total = len(root_files) + sum(subfolder_counts.values())

    categories = defaultdict(int)
    authors = defaultdict(int)
    no_author = 0
    no_isbn = 0
    no_title = 0
    no_category = 0
    no_vortexy = 0
    would_skip = 0
    duplicate_titles = defaultdict(list)
    dup_ids = set()

    for rel_path in md_files:
        filepath = os.path.join(vault_path, rel_path)
        try:
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                text = f.read()
        except Exception:
            continue

        fm, body = parse_frontmatter(text)
        existing_author = fm.get("author", "").strip("[]").strip()
        existing_category = fm.get("category", "Uncategorized")
        existing_isbn = fm.get("isbn", "").strip()
        existing_title = extract_heading(body) or ""
        is_vortexy = "Generated by Vortexy Graph Architect" in text

        if not is_vortexy:
            no_vortexy += 1

        cat = existing_category or "Uncategorized"
        categories[cat] += 1
        if not existing_category or existing_category == "Uncategorized":
            no_category += 1

        author_key = existing_author.lower() if existing_author else "unknown"
        if author_key in ("", "unknown", "unknown author", "unknown auto"):
            no_author += 1
            author_key = "unknown"
        else:
            authors[author_key] += 1

        if not existing_isbn:
            no_isbn += 1
        if not existing_title:
            no_title += 1
        if (not existing_author or author_key == "unknown") and not existing_title:
            would_skip += 1

        title_key = existing_title.lower().strip()
        if title_key:
            duplicate_titles[title_key].append(rel_path)

    for paths in duplicate_titles.values():
        if len(paths) > 1:
            dup_ids.update(paths)

    if json_out:
        report = {
            "total_notes": total,
            "root_notes": len(root_files),
            "no_author": no_author,
            "no_isbn": no_isbn,
            "no_title": no_title,
            "no_category": no_category,
            "non_vortexy": no_vortexy,
            "would_skip": would_skip,
            "duplicates": len(dup_ids),
            "subfolders": dict(subfolder_counts),
            "categories": dict(categories),
            "top_authors": sorted(authors.items(), key=lambda x: -x[1])[:10],
        }
        print(json.dumps(report, indent=2, ensure_ascii=False))
        return

    print(f"=== Vault Health Report ===")
    print(f"  Vault: {vault_path}")
    print()

    print("=== Subfolders ===")
    for folder in sorted(subfolder_counts.keys()):
        print(f"  {folder}: {subfolder_counts[folder]}")
    print(f"  (root): {len(root_files)}")
    print()

    print("=== Categories ===")
    for cat, cnt in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {cnt}")
    print()

    print("=== Health ===")
    print(f"  Total .md notes:       {total}")
    print(f"  No author:             {no_author}")
    print(f"  No ISBN:               {no_isbn}")
    print(f"  No title heading:      {no_title}")
    print(f"  No category:           {no_category}")
    print(f"  Non-Vortexy (orphan):  {no_vortexy}")
    print(f"  Would be skipped:      {would_skip}")
    print(f"  Duplicate titles:      {len(dup_ids)} files")
    print()

    print("=== Top 10 Authors ===")
    top = sorted(authors.items(), key=lambda x: -x[1])
    for author_name, cnt in top[:10]:
        print(f"  {author_name}: {cnt}")
    print()

    cache_path = os.path.join(CORE_DIR, "data", "metadata_cache.json")
    if os.path.exists(cache_path):
        with open(cache_path, "r", encoding="utf-8") as f:
            cache = json.load(f)
        empty = sum(1 for v in cache.values() if not v or v == {})
        size_kb = os.path.getsize(cache_path) / 1024
        print("=== Metadata Cache ===")
        print(f"  Total entries: {len(cache)}")
        print(f"  Empty entries: {empty}")
        print(f"  Cache size:    {size_kb:.1f} KB")
        print()

    if details and dup_ids:
        print("=== Duplicate Title Details ===")
        for title_key, paths in sorted(duplicate_titles.items()):
            if len(paths) > 1:
                print(f"  '{title_key}':")
                for p in paths:
                    print(f"    - {p}")


if __name__ == "__main__":
    cfg = load_config()
    parser = argparse.ArgumentParser(description="Vault health report")
    parser.add_argument("--vault", default=cfg.get("vault_path", ""), help="Obsidian vault path")
    parser.add_argument("--json", action="store_true", default=False, help="Output JSON")
    parser.add_argument("--details", action="store_true", default=False, help="Show duplicate titles")
    args = parser.parse_args()
    vault_report(args.vault, json_out=args.json, details=args.details)
